/* SPDX-License-Identifier: LicenseRef-OBINexus-1.0
 *
 * mathlib bare -- the transcript's library exactly as it was.
 *
 *     int add(int a, int b) { return a + b; }
 *
 * and nothing else.  No ABI table, no version, no declaration of what it
 * provides.  Compile it, link it, ship it, change it, ship it again.
 *
 * The loader refuses it with MMUKO_LOAD_E_NO_TABLE.
 *
 * This is worth being explicit about, because it is a real cost and not a free
 * win: MMUKO cannot make an arbitrary pre-existing .so safe.  What it can do
 * is refuse to pretend.  An object that has never stated its contract offers
 * nothing to compare against, and binding to it would be a guess wearing the
 * costume of a check.  Migration means giving each object a table -- which is
 * one macro block per library, generated by the same compiler pass that
 * generates the code.
 */

#if defined(_WIN32)
#  define BARE_PUBLIC __declspec(dllexport)
#elif defined(__GNUC__)
#  define BARE_PUBLIC __attribute__((visibility("default")))
#else
#  define BARE_PUBLIC
#endif

BARE_PUBLIC int add(int a, int b);
BARE_PUBLIC int mul(int a, int b);

BARE_PUBLIC int add(int a, int b)
{
    return a + b;
}

BARE_PUBLIC int mul(int a, int b)
{
    return a * b;
}
